#version: "3.9"

services:
  wp:
    build:
      context: ${PROJECT_BASE}
      dockerfile: docker/Dockerfile.wordpress
      args:
        WORDPRESS_IMAGE: ${WORDPRESS_IMAGE}
    container_name: ${PROJECT_NAME}_wp
    environment:
      WORDPRESS_DB_HOST: ptekwpdev_db
      WORDPRESS_DB_USER: ${SQLDB_USER}
      WORDPRESS_DB_PASSWORD: ${SQLDB_PASSWORD}
      WORDPRESS_DB_NAME: ${PROJECT_NAME}_db
    volumes:
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/assets:/var/www/html/wp-content
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/certs:/etc/ssl/certs
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/secrets:/run/secrets
    networks:
      - frontend
      - backend
    restart: unless-stopped

  wpcli:
    build:
      context: ${PROJECT_BASE}
      dockerfile: config/Dockerfile.wpcli
      args:
        WORDPRESS_IMAGE: ${WORDPRESS_IMAGE}
    container_name: ${PROJECT_NAME}_wpcli
    depends_on:
      - wp
    volumes:
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/assets:/var/www/html/wp-content
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/certs:/etc/ssl/certs
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/secrets:/run/secrets
    networks:
      - frontend
      - backend
    entrypoint: wp

  proxy:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_proxy
    depends_on:
      - wp
    volumes:
      - ${BUILD_HOME}/config/proxy/nginx.tpl.conf:/etc/nginx/conf.d/default.conf:ro
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/assets:/var/www/html/wp-content
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/certs:/etc/ssl/certs
    networks:
      - frontend
    ports:
      - "${WORDPRESS_PORT}:80"
      - "${WORDPRESS_SSL_PORT:-443}:443"
    restart: unless-stopped

networks:
  frontend:
    name: ${FRONTEND_NETWORK}
    driver: bridge

  backend:
    external: true
    name: ${BACKEND_NETWORK}

