#version: "3.9"

services:
  wp:
    build:
      context: ${PROJECT_BASE}
      dockerfile: docker/Dockerfile.wordpress
      args:
        WORDPRESS_IMAGE: ${WORDPRESS_IMAGE}
    container_name: ${PROJECT_NAME}_wp
    environment:
      WORDPRESS_DB_HOST: sqldb #${SQLDB_HOST}
      WORDPRESS_DB_USER: ${SQLDB_USER}
      WORDPRESS_DB_PASSWORD: ${SQLDB_PASSWORD}
      WORDPRESS_DB_NAME: ${SQLDB_NAME}
    volumes:
      #- ${PROJECT_BASE}/wordpress:/var/www/html/wp-content
      - ptekwpdev_assets_volume:/var/www/html/wp-content
    networks:
      - frontend_network
      - backend_network
    restart: unless-stopped

  wpcli:
    build:
      context: ${PROJECT_BASE}
      dockerfile: config/Dockerfile.wpcli
      args:
        WORDPRESS_IMAGE: ${WORDPRESS_IMAGE}
    container_name: ${PROJECT_NAME}_wpcli
    depends_on:
      - wp
    command: tail -f /dev/null
    volumes:
      - ptekwpdev_assets_volume:/var/www/html/wp-content
    networks:
      - frontend_network
    entrypoint: wp

  proxy:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_proxy
    env_file: 
      - .env
    depends_on:
      - wp
    volumes:
      # NGINX Conf and SSL Certs
      - ${PROJECT_BASE}/config/proxy/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${PROJECT_BASE}/config/proxy/certs:/etc/nginx/certs:ro
    networks:
      - frontend_network
    ports:
      - "${WORDPRESS_PORT}:80"
      - "${WORDPRESS_SSL_PORT:-443}:443"
    restart: unless-stopped

volumes:
  ptekwpdev_assets_volume:

networks:
  frontend_network:
    name: ${FRONTEND_NETWORK}
    driver: bridge

  backend_network:
    external: true
    name: ${BACKEND_NETWORK}

