#version: "3.9"

services:
  sqldb:
    image: mysql:8.0
    container_name: ${SQLDB_CONTAINER}
    environment:
      MYSQL_ROOT_PASSWORD: ${SQLDB_ROOT_PASS}
    volumes:
      - ptekwpdev_db_volume:/var/lib/mysql
    networks:
      - backend
    ports:
      - "${SQLDB_PORT}:3306"
    restart: unless-stopped

  sqladmin:
    image: adminer
    container_name: ${SQLADMIN_CONTAINER}
    ports:
      - "${SQLADMIN_PORT}:8080"
    networks:
      - backend
    restart: unless-stopped

volumes:
  ptekwpdev_assets_volume:
  ptekwpdev_db_volume:

networks:
  backend:
    name: ${BACKEND_NETWORK}
    driver: bridge
