#version: "3.9"

services:
  ${PROJECT_NAME}_wp:
    image: wordpress:6.7
    container_name: ${PROJECT_NAME}_wp
    environment:
      WORDPRESS_DB_HOST: ptekwpdev_db
      WORDPRESS_DB_USER: ${PROJECT_NAME}_user
      WORDPRESS_DB_PASSWORD: ${PROJECT_NAME}_pass
      WORDPRESS_DB_NAME: ${PROJECT_NAME}_db
    volumes:
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/assets:/var/www/html/wp-content
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/certs:/etc/ssl/certs
      - ${HOME}/.ptekwpdev/projects/${PROJECT_NAME}/secrets:/run/secrets
    networks:
      - ptekwpdev_net
    ports:
      - "${PROJECT_PORT}:80"
    restart: unless-stopped

networks:
  ptekwpdev_net:
    external: true