services:
  ptekwpdev-assets:
    container_name: ${ASSETS_CONTAINER}
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null   # ðŸ‘ˆ keeps the container running
    volumes:
      - ${ASSETS_VOLUME}:${ASSETS_ROOT}   # ðŸ‘ˆ named volume 
    restart: unless-stopped

volumes:
  ptekwpdev_assets_volume:   # ðŸ‘ˆ declare the volume
    name: ${ASSETS_VOLUME}