#
# We build a Resource only Volume "ptekdevwp-assets" into a dummy container
# This volume can be used in other containers to locate local plugins themese and
# other static assets.
#
services:
  ptekwpdev-assets:
    image: alpine:latest
    container_name: ptkewpdev_assets
    build:
      context: .
    # Keep alive for debug purpose
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ptekwpdev_assets:/usr/src/ptekwpdev

volumes:
  ptekwpdev_assets:
    name: "ptekwpdev_assets"