services:
  ptekwpdev-assets:
    container_name: ptekwpdev_assets
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null   # ğŸ‘ˆ keeps the container running
    volumes:
      - ptekwpdev_assets_volume:/usr/src/ptekwpdev/assets   # ğŸ‘ˆ named volume
    restart: unless-stopped

volumes:
  ptekwpdev_assets_volume:   # ğŸ‘ˆ declare the volume
    name: ptekwpdev_assets_volume